# Generated by Django 5.0.2 on 2024-03-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0002_alter_key_keyname_alter_permission_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='total_quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
