# Generated by Django 5.0.2 on 2024-03-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapp', '0004_alter_permission_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='level',
            field=models.CharField(choices=[('Read', 'Read'), ('Write', 'Write')], default='Read', max_length=10),
        ),
    ]
